package com.vehiclemanagement.agent;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * One-time enrollment code for pairing a desktop agent with a site.
 * Generated by website admin, consumed by Tauri app during initial setup.
 */
@Entity
@Table(name = "site_agent_enrollment_code")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SiteAgentEnrollmentCode {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "site_id", nullable = false)
    private UUID siteId;

    @Column(name = "code", nullable = false, unique = true)
    private String code;

    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    @Column(name = "used_at")
    private LocalDateTime usedAt;

    @Column(name = "used_by_agent_id")
    private UUID usedByAgentId;

    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    @Column(name = "created_by_user_id")
    private UUID createdByUserId;

    public boolean isValid() {
        return usedAt == null
            && expiresAt.isAfter(LocalDateTime.now());
    }

    public boolean isExpired() {
        return expiresAt.isBefore(LocalDateTime.now());
    }

    public void markUsed(UUID agentId) {
        this.usedAt = LocalDateTime.now();
        this.usedByAgentId = agentId;
    }
}
