-- DAI-271: rename application RBAC roles to the tenant-aware role set.
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;

UPDATE users
SET role = CASE role
    WHEN 'ADMIN' THEN 'PLATFORM_ADMIN'
    WHEN 'APPROVER' THEN 'TENANT_ADMIN'
    WHEN 'SECURITY_OFFICER' THEN 'TENANT_ADMIN'
    WHEN 'USER' THEN 'MEMBER'
    ELSE role
END
WHERE role IN ('ADMIN', 'APPROVER', 'SECURITY_OFFICER', 'USER');

ALTER TABLE users ADD CONSTRAINT users_role_check
    CHECK (role IN ('PLATFORM_ADMIN', 'TENANT_ADMIN', 'SITE_MANAGER', 'SECURITY_GUARD', 'MEMBER'));

COMMENT ON COLUMN users.role IS
    'User role: PLATFORM_ADMIN, TENANT_ADMIN, SITE_MANAGER, SECURITY_GUARD, or MEMBER.';
