-- V82: Enrollment codes and camera runtime health
--
-- 1. site_agent_enrollment_code: One-time codes for pairing desktop apps
-- 2. camera_runtime_health: Separates runtime state from desired configuration

-- ---- Enrollment codes -------------------------------------------------------
-- Short-lived, one-time codes for agent enrollment. Generated by website admin,
-- consumed by desktop app during pairing.

CREATE TABLE site_agent_enrollment_code (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::uuid,
    site_id     UUID NOT NULL REFERENCES site(id) ON DELETE CASCADE,
    code        VARCHAR(20) NOT NULL UNIQUE,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at     TIMESTAMP WITH TIME ZONE,
    used_by_agent_id UUID REFERENCES site_agent(id) ON DELETE SET NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id UUID,
    CONSTRAINT fk_enrollment_tenant FOREIGN KEY (tenant_id) REFERENCES tenant(id)
);

CREATE INDEX idx_enrollment_tenant_id ON site_agent_enrollment_code(tenant_id);
CREATE INDEX idx_enrollment_site_id ON site_agent_enrollment_code(site_id);
CREATE INDEX idx_enrollment_code ON site_agent_enrollment_code(code) WHERE used_at IS NULL;

ALTER TABLE site_agent_enrollment_code ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_agent_enrollment_code FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON site_agent_enrollment_code
    USING      (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

GRANT SELECT, INSERT, UPDATE, DELETE ON site_agent_enrollment_code TO app_rls, app_admin;

-- ---- Camera runtime health --------------------------------------------------
-- Runtime state separate from camera desired configuration. Tracks connection state,
-- frame metrics, and errors reported by the agent.

CREATE TABLE camera_runtime_health (
    camera_id          UUID PRIMARY KEY REFERENCES camera(id) ON DELETE CASCADE,
    tenant_id          UUID NOT NULL DEFAULT NULLIF(current_setting('app.tenant_id', true), '')::uuid,
    agent_id           UUID REFERENCES site_agent(id) ON DELETE SET NULL,
    -- Runtime connection state
    connection_state   VARCHAR(30) NOT NULL DEFAULT 'unassigned'
        CHECK (connection_state IN ('unassigned', 'assigned', 'connecting', 'streaming', 'error', 'stopped')),
    -- Frame-based health (camera online = agent online AND recent frame)
    last_frame_at      TIMESTAMP WITH TIME ZONE,
    fps                NUMERIC(5,2),
    width              INTEGER,
    height             INTEGER,
    codec              VARCHAR(20),
    -- Diagnostics
    reconnect_count    INTEGER NOT NULL DEFAULT 0,
    queue_depth        INTEGER NOT NULL DEFAULT 0,
    error_code         VARCHAR(50),
    error_message_safe TEXT,
    -- Config version applied by agent (incremented on camera CRUD)
    config_version     INTEGER,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_runtime_tenant FOREIGN KEY (tenant_id) REFERENCES tenant(id)
);

CREATE INDEX idx_runtime_tenant_id ON camera_runtime_health(tenant_id);
CREATE INDEX idx_runtime_agent_id ON camera_runtime_health(agent_id);
CREATE INDEX idx_runtime_state ON camera_runtime_health(connection_state);
-- Query cameras needing offline sweep
CREATE INDEX idx_runtime_last_frame ON camera_runtime_health(last_frame_at)
    WHERE connection_state = 'streaming';

ALTER TABLE camera_runtime_health ENABLE ROW LEVEL SECURITY;
ALTER TABLE camera_runtime_health FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON camera_runtime_health
    USING      (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid);

GRANT SELECT, INSERT, UPDATE, DELETE ON camera_runtime_health TO app_rls, app_admin;

-- ---- Add config_version to camera table ------------------------------------
-- Incremented whenever camera configuration changes. Agents poll config with
-- this version to detect changes and restart workers.

ALTER TABLE camera ADD COLUMN config_version INTEGER NOT NULL DEFAULT 1;

CREATE INDEX idx_camera_config_version ON camera(site_id, config_version);
