import type { Employee, Department, AccessLevel, CustomField, DocumentLibrary } from "./types"

export const mockDepartments: Department[] = [
  {
    id: "1",
    name: "Department Name",
    description: "Main department",
    employeeCount: 26,
    createdAt: "2025-04-26T02:07:55Z",
    updatedAt: "2025-04-26T02:07:55Z",
  },
  {
    id: "2",
    name: "Tiểu Đoàn 9",
    description: "Battalion 9",
    employeeCount: 28,
    createdAt: "2025-04-25T16:06:42Z",
    updatedAt: "2025-04-25T16:06:42Z",
  },
  {
    id: "99",
    name: "Khách",
    description: "Guest department",
    employeeCount: 0,
    createdAt: "2025-04-26T09:37:50Z",
    updatedAt: "2025-04-26T09:37:50Z",
  },
  {
    id: "3",
    name: "Tiểu Đoàn 7",
    description: "Battalion 7",
    employeeCount: 42,
    createdAt: "2025-04-28T16:56:47Z",
    updatedAt: "2025-04-28T16:56:47Z",
  },
  {
    id: "4",
    name: "Khối Trực Thuộc",
    description: "Direct reporting unit",
    employeeCount: 55,
    createdAt: "2025-04-29T09:10:00Z",
    updatedAt: "2025-04-29T09:10:00Z",
  },
  {
    id: "5",
    name: "Tiểu Đoàn 8",
    description: "Battalion 8",
    employeeCount: 31,
    createdAt: "2025-04-29T10:08:54Z",
    updatedAt: "2025-04-29T10:08:54Z",
  },
  {
    id: "6",
    name: "Ban Tham Mưu",
    description: "Staff department",
    employeeCount: 22,
    createdAt: "2025-04-29T14:01:14Z",
    updatedAt: "2025-04-29T14:01:14Z",
  },
  {
    id: "7",
    name: "Ban Hậu Cần - Kỹ Thuật",
    description: "Logistics and Technical department",
    employeeCount: 9,
    createdAt: "2025-04-29T14:28:36Z",
    updatedAt: "2025-04-29T14:28:36Z",
  },
  {
    id: "8",
    name: "Cán Tin Khối Trực Thuộc",
    description: "Direct unit canteen",
    employeeCount: 5,
    createdAt: "2025-05-02T07:43:19Z",
    updatedAt: "2025-05-02T07:43:19Z",
  },
]

export const mockEmployees: Employee[] = [
  {
    id: "836fd592-b411-4bc2-8bc2-d20bb7b65d73",
    employeeId: "248",
    name: "Nguyễn Duy Linh",
    firstName: "Duy Linh",
    lastName: "Nguyễn",
    email: "nguyen.duy.linh@company.com",
    phone: "0123456789",
    department: "Tiểu Đoàn 8",
    position: "Nhân viên",
    hireDate: "2025-01-15",
    status: "active",
    accessLevel: "general",
    permissions: ["read"],
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-01-15T00:00:00Z",
  },
  {
    id: "9eb71868-eb4f-4dbf-b734-74e65f6384d1",
    employeeId: "247",
    name: "Đoàn Đình Độ",
    firstName: "Đình Độ",
    lastName: "Đoàn",
    email: "doan.dinh.do@company.com",
    phone: "0123456790",
    department: "Department Name",
    position: "Trưởng phòng",
    hireDate: "2024-12-01",
    status: "active",
    accessLevel: "admin",
    permissions: ["read", "write", "delete"],
    createdAt: "2024-12-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "f6799dc3-4cc8-4014-b3d7-91753751ceac",
    employeeId: "246",
    name: "Võ Hữu Trường",
    firstName: "Hữu Trường",
    lastName: "Võ",
    email: "vo.huu.truong@company.com",
    phone: "0123456791",
    department: "Ban Tham Mưu",
    position: "Nhân viên",
    hireDate: "2024-11-15",
    status: "active",
    accessLevel: "general",
    permissions: ["read"],
    createdAt: "2024-11-15T00:00:00Z",
    updatedAt: "2024-11-15T00:00:00Z",
  },
  {
    id: "cbf559e6-09aa-43b7-96fa-6a24e98a8976",
    employeeId: "245",
    name: "Phạm Thị Thảo",
    firstName: "Thị Thảo",
    lastName: "Phạm",
    email: "pham.thi.thao@company.com",
    phone: "0123456792",
    department: "Ban Tham Mưu",
    position: "Nhân viên",
    hireDate: "2024-10-20",
    status: "active",
    accessLevel: "general",
    permissions: ["read"],
    createdAt: "2024-10-20T00:00:00Z",
    updatedAt: "2024-10-20T00:00:00Z",
  },
]

export const mockAccessLevels: AccessLevel[] = [
  {
    id: "1",
    name: "General",
    description: "Basic access level for regular employees",
    permissions: ["read"],
    isDefault: true,
  },
  {
    id: "2",
    name: "Restricted",
    description: "Limited access for temporary or contract workers",
    permissions: ["read_limited"],
    isDefault: false,
  },
  {
    id: "3",
    name: "Admin",
    description: "Full administrative access",
    permissions: ["read", "write", "delete", "admin"],
    isDefault: false,
  },
]

export const mockCustomFields: CustomField[] = [
  {
    id: "1",
    name: "Employee Type",
    type: "select",
    options: ["Official Staff", "Probation", "Contract Worker", "Non Contract"],
    required: true,
    category: "General",
    order: 1,
  },
  {
    id: "2",
    name: "Hire Type",
    type: "select",
    options: ["Contract Worker", "Non Contract"],
    required: false,
    category: "General",
    order: 2,
  },
  {
    id: "3",
    name: "Job Title",
    type: "text",
    required: false,
    category: "Position",
    order: 3,
  },
  {
    id: "4",
    name: "Street",
    type: "text",
    required: false,
    category: "Address",
    order: 4,
  },
  {
    id: "5",
    name: "Birthplace",
    type: "text",
    required: false,
    category: "Personal",
    order: 5,
  },
  {
    id: "6",
    name: "Country",
    type: "text",
    required: false,
    category: "Address",
    order: 6,
  },
  {
    id: "7",
    name: "Home Phone",
    type: "text",
    required: false,
    category: "Contact",
    order: 7,
  },
  {
    id: "8",
    name: "Home Address",
    type: "textarea",
    required: false,
    category: "Address",
    order: 8,
  },
  {
    id: "9",
    name: "Office Phone",
    type: "text",
    required: false,
    category: "Contact",
    order: 9,
  },
]

export const mockDocuments: DocumentLibrary[] = [
  {
    id: "1",
    name: "Pass List",
    type: "document",
    size: 240,
    uploadDate: "2025-01-15",
    uploadedBy: "Cho phép Thu",
    permissions: ["read", "write"],
    url: "/documents/pass-list.pdf",
  },
  {
    id: "2",
    name: "Forbidden List",
    type: "document",
    size: 0,
    uploadDate: "2025-01-15",
    uploadedBy: "Thu viện danh",
    permissions: ["read"],
    url: "/documents/forbidden-list.pdf",
  },
]
