server:
  port: 8080

spring:
  application:
    name: vehicle-management-api
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
      file-size-threshold: 2KB
      location: /app/temp
      resolve-lazily: false
  
  datasource:
    url: jdbc:postgresql://postgres:5432/vehicle_management
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.vehiclemanagement: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
